# Generated by Django 3.0.8 on 2020-11-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Contact',
        ),
    ]
